apiVersion: v1
kind: Service
metadata:
  name: ils-db
  labels:
    app: reroils
    tier: db
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30013
      name: db
  selector:
    app: reroils
    tier: db