apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ils-flower
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reroils
        tier: flower
    spec:
      containers:
      - name: reroils-flower
        image: mher/flower
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: reroils-app
              key: worker-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: reroils-app
              key: worker-password
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 5555
          name: flower
        args: ['--broker=amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@ils-worker:$(ILS_WORKER_SERVICE_PORT_WORKER)// --broker_api=http://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@ils-worker:$(ILS_WORKER_SERVICE_PORT_UI)/api/']
      