apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reroilsfrontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: reroils
        tier: reroilsfrontend
    spec:
      containers:
      - name: reroils-app
        image: rero/reroils-app:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          #value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          value: env
        ports:
        - containerPort: 5000
